spring:
  application:
    name: big_event
    version: 1.0.0
    description: big_event
    author: CH_ywx
    email: waisinyeo@gmail.com
  profiles:
    active: druid
mybatis:
  configuration:
    auto-mapping-behavior: full
    map-underscore-to-camel-case: true
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    log-prefix: Mybatis
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: io.xccit.event.entity
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: '用户信息'
      paths-to-match: '/user/**'
      packages-to-scan: io.xccit.event.controller
    - group: '文章信息'
      paths-to-match: '/article/**'
      packages-to-scan: io.xccit.event.controller
    - group: '分类信息'
      paths-to-match: '/category/**'
      packages-to-scan: io.xccit.event.controller
    - group: '文件上传'
      paths-to-match: '/file/**'
      packages-to-scan: io.xccit.event.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn


aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    accessKeyId: Your AccessKeyId
    accessKeySecret: Your AccessKeySecret
    bucketName: Your BucketName


